### ISSUE TITLE
problem with new animation

### ISSUE THREAD

**Issue by ZaitianWang** [JerryZhangZZY/EBU6304-2021-Software-Engineering-Group-111#18]
1. Unexpected page flashes when loading welcome page: login page appears for a moment before welcome page scrolls down (when first launch or back from any other pages)
2. Exit button can sometimes exist after (clicking exit button and) back to welcome page

**Comment by JerryZhangZZY** [comment]
1. Yes, this is what I expected.
2. I tried millions of ways to solve it resulting in failure...
