### ISSUE TITLE
Unexpected value occurs in test

### ISSUE THREAD

**Issue by ZaitianWang** [JerryZhangZZY/EBU6304-2021-Software-Engineering-Group-111#48]
State.getPc() appears to be very lager (up to 17 in my case), which should in any circumstance be no more than 8 if runs properly.
Check your for-loop, may need reseting.
This will lead to fatal error when integrated.
BTW, better explain the relationship between `RepeatedTest` and `for` loops in comments

**Comment by BHobbes** [comment]
The for loop is designed to simulate a user who comes to SeatSelectionPanel for several times and clicks several seat buttons during a single check-in.
Repeat testing can be viewed as different check-in process.

**Comment by ZaitianWang** [comment]
> The for loop is designed to simulate a user who comes to SeatSelectionPanel for several times and clicks several seat buttons during a single check-in. Repeat testing can be viewed as different check-in process.

thank you for the explanation

**Comment by ZaitianWang** [comment]
The same problem still exits in meal selection test, would you be so kind to fix it, too? @BHobbes 

Much thanks

**Comment by ZaitianWang** [comment]
once again, in bill confirmation test
