### ISSUE TITLE
Auto exit function enhancement

### ISSUE THREAD

**Issue by zhuantomato** [JerryZhangZZY/EBU6304-2021-Software-Engineering-Group-111#50]
#34 Still needs to be enhanced: Timer is not completely synchronized with the Clock.

**Comment by ZaitianWang** [comment]
It would be better if a hint is provided, like "auto exit in " + timer + " seconds" @zhuantomato

**Comment by JerryZhangZZY** [comment]
@ZaitianWang
The first version is what you described.

**Comment by JerryZhangZZY** [comment]
@zhuantomato
Timer should start at seat selection page instead of flight selection.

**Comment by JerryZhangZZY** [comment]
@zhuantomato
OR: timer starts when unlocking the screen and reset after finishing a flight check-in.

**Comment by zhuantomato** [comment]
@ZaitianWang @JerryZhangZZY The way of displaying the timer is easy to modify at any stage.

> It would be better if a hint is provided, like "auto exit in " + timer + " seconds" @zhuantomato



> @ZaitianWang The first version is what you described.

**Comment by ZaitianWang** [comment]
> @ZaitianWang The first version is what you described.

remind me, would you?
