### ISSUE TITLE
Admin console kills the entire software

### ISSUE THREAD

**Issue by JerryZhangZZY** [JerryZhangZZY/EBU6304-2021-Software-Engineering-Group-111#51]
Call the admin console and press <kbd>Alt</kbd> + <kbd>F4</kbd> to kill it, then the entire software crashes 233333.

**Comment by ZaitianWang** [comment]
I did not change the console into a panel because that needs more effort to lock other components in the main frame, especially when panel loading processes have been change in way that I am not very familiar with. Exit-on-close is used instead. Anyway, alt-f4-crashing problem is resolved.

**Comment by JerryZhangZZY** [comment]
LGTM
