### ISSUE TITLE
Stereotypes of UML classes

### ISSUE THREAD

**Issue by ZaitianWang** [JerryZhangZZY/EBU6304-2021-Software-Engineering-Group-111#56]
I think classes like dbReader should be control classes, as "Controller" in page 16, W3_Rec2 slides, who fetch data and return them to a gui. Considering them as  boundary classes is not very appropiate.

Config and Theme perhaps should be entity classes, like State. You may think its weird because we do not "create" instance of these classes. But, that is because our product is a stand-alone software. If the whole system contians many kiosks in the airport, I am sure we need to create config, theme, and state instance for process on each machine.

**Comment by JerryZhangZZY** [comment]
Reasonable.
